// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9WPLrCxikP1Xl_us48pRAhEZjljX7jDU',
    appId: '1:326619305769:web:5d3e19d6edb2620b3a8938',
    messagingSenderId: '326619305769',
    projectId: 'tik-tok-clone-backend',
    authDomain: 'tik-tok-clone-backend.firebaseapp.com',
    storageBucket: 'tik-tok-clone-backend.appspot.com',
    measurementId: 'G-6J1DQH8VD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArPJL3gDeG_qlL-egjTuVoHCUvLIUb-JQ',
    appId: '1:326619305769:android:747723d8723a7f1c3a8938',
    messagingSenderId: '326619305769',
    projectId: 'tik-tok-clone-backend',
    storageBucket: 'tik-tok-clone-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEUmI0tgh4MLvbe-gMfE9BxhxL1ioMIN8',
    appId: '1:326619305769:ios:2bceeae4fd50ecf73a8938',
    messagingSenderId: '326619305769',
    projectId: 'tik-tok-clone-backend',
    storageBucket: 'tik-tok-clone-backend.appspot.com',
    iosClientId: '326619305769-n2fdpp4futc4nh4pklp6og3cppo112t1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikTokClone',
  );
}
